sudo: required
services:
  - docker

before_install:
  - docker build -t widesoftware/docker-react -f Dockerfile.dev .

script:
  - docker run widesoftware/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-gabs"
  env: "DockerGabs-env"
  bucket_name: "elasticbeanstalk-us-west-2-769177069788"
  bucket_path: "docker-gabs"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
